import src1 from "../assets/src1.jpg";
import src2 from "../assets/src2.JPG";
import src3 from "../assets/src3.JPG";
import src4 from "../assets/src4.JPG";
import src5 from "../assets/src5.jpg";
import src6 from "../assets/src6.JPG";

export const src = [
  { img: src1, name: "Bowls 1" },  
  { img: src2, name: "Bowls 2" },
  { img: src3, name: "Bowls 3" },
  { img: src4, name: "Bowls 4" },
  { img: src5, name: "Bowls 5" },
  { img: src6, name: "Bowls 6" },
];
export const categories = ["All","Breakfast", "Lunch", "Dinner", "Snacking", "Party"];

export const menuItems = [
  "Breakfast",
  "Bowls",
  "Superbowls",
  "Pasta",
  "Noodles",
  "Burgers",
  "Wraps",
  "Desserts",
  "Beverages",
];

export const carddata = [
  {
    thirdPartyDescription:
      "Immerse yourself in a realm of unparalleled epicurean delight with this on-the-go meal, crafted to satisfy food truck enthusiasts seeking an extraordinary dining experience. a harmonious blend of perfectly grilled paneer and succulent slow-roasted pulled tofu, nestled atop a bed of flavorful Mexican rice. A hearty platter perfect for indulging in a satisfying and flavorful meal.\nEnergy 505 Kcal, Carbs 51 gms, Protein 19 gms, Fiber 6 gms, Fat 26 gms",
    i: 13453,
    t: "Cocktail Tofu Rice Bowls",
    shd: "Rice, Tofu, Tomato Sauce, Kidney Beans, Butter Tossed Veggies, Bechamel Sauce.",
    mainCategory: "Bowls",
    p: 149,
    mrp: 299,
    im: "https://d3gy1em549lxx2.cloudfront.net/e19f4994-14c0-4bfa-80ac-24a7cc05e907.JPG",
    ct: ["lunch", "dinner"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "With a rich and savory broth that combines soft noodles and succulent chicken, our spicy satay chicken ramen will tantalise your senses. It's a bowl of warmth and spice that pleases with every slurp, bursting with a colorful variety of vegetables including cabbage, carrot, bell peppers, and broccoli, and laced with the kick of red chilli and the sweetness of honey.\nEnegry-334 Kcal, Fat-9.19 gms, Carbs-43.22 gms, Fiber-6.2 gms, Protein-21.7 gms, Sugar-12.7 gms",
    i: 14423,
    t: "Spicy Satay  Ramen",
    shd: " Noodles, Egg, Cabbage, Carrot, Onion, Bell Peppers, Broccoli, Beans, Red Chilli, Honey, Corn Flour",
    mainCategory: "Noodles",
    p: 149,
    mrp: 299,
    im: "https://d3gy1em549lxx2.cloudfront.net/90bbdd8c-f6e5-44ac-a7d9-e3c10c7783a4.JPG",
    ct: ["lunch", "dinner", "snacking", "party"],
    egg: true,
  },
  {
    thirdPartyDescription:
      "Our Taiwanese Ramen, which has crisp noodles dipped in a flavorful broth, will transport you to Taiwan and its mouthwatering flavors. With each spoonful, this culinary adventure promises to awaken your senses, enhanced by a medley of crunchy vegetables including bell peppers, cabbage, and carrots, and enhanced with the robust kick of chilli paste.\nEnegry-370 Kcal, Fat-14.12 gms, Carbs-38.11 gms, Fiber-5.7 gms, Protein-9.23 gms, Sugar-21.13 gms",
    i: 14425,
    t: "Taiwanese Ramen",
    mainCategory: "Noodles",
    shd: "Noodles, Cabbage, Onion, Carrot, Mushroom, Bell Peppers, Chilli Paste, Corn Flour",
    p: 149,
    mrp: 299,
    im: "https://d3gy1em549lxx2.cloudfront.net/af6ed6ca-bf23-4cf3-b2ed-a0090b1f8b53.JPG",
    ct: ["lunch", "dinner", "snacking", "party"],
    egg: true,
  },
  {
    thirdPartyDescription:
      "Savor the delightful combination of sweet and savory flavors found in our Honey Soy Stir-Fry Ramen, which features colorful vegetables mixed with tender noodles. With a hint of chile paste and the seductive tastes of soy and honey, it's a perfectly gratifying dish that adds flavor and comfort to every bite.\nEnegry-262 Kcal, Fat-5.47 gms, Carbs-47.62 gms, Fiber-6.6 gms, Protein-9.43 gms, Sugar-14.77 gms",
    i: 14427,
    t: "Honey Soy Stir Fry Ramen",
    shd: "Noodles, Cabbage, Onion, Carrot, Beans, Broccoli, Bell Peppers, Chilli Paste, Corn Flour, Honey",
    mainCategory: "Bowls",
    p: 149,
    mrp: 299,
    im: "https://d3gy1em549lxx2.cloudfront.net/ec24e1f3-a5ae-449a-b79f-930cbc5ed7bd.JPG",
    ct: ["lunch", "dinner"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "With a colorful combination of cabbage, onion, carrot, and bell peppers, our Cilantro Lime Ramen will give your taste buds a refreshing burst of flavor. Enhanced by the piquant bite of lemon and the heady perfume of cilantro, it's a delicious blend of tastes that awakens the senses with each sip.\nEnegry-227 Kcal, Fat-4.54 gms, Carbs-40.87 gms, Fiber-5.9 gms, Protein-9.15 gms, Sugar-9.43 gms",
    i: 14429,
    t: "Cilantro Lime Ramen",
    shd: "Noodles, Cabbage, Onion, Carrot, Bell Peppers, Lemon, Corn Flour",
    mainCategory: "Noodles",
    p: 149,
    mrp: 299,
    im: "https://d3gy1em549lxx2.cloudfront.net/ddf7ef51-23cc-46d9-a2a6-928059e5844e.JPG",
    ct: ["lunch", "dinner", "party"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Refreshing fried rice mixed in juicy veggies and seasoned with a saucy manchurian flavour.\nEnergy 540 Kcal, Fat 22 gms, Carbs 69 gms, Fiber 4 gms, Protein 10 gms.",
    i: 12775,
    t: "Veg Manchurian Fried Rice Bowls",
    mainCategory: "Superbowls",
    p: 149,
    mrp: 299,
    im: "https://d3gy1em549lxx2.cloudfront.net/1307cd7d-f525-40ca-ac41-f5fc638738cf.jpg",
    ct: ["lunch", "dinner"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Introduce your taste buds to the delicious new Signature Roast Rice Bowls. Bristish style glaced with caramelised onion, pan seared mushroom and crushed blackpeppercorns for the perfect taste! All you can wish for combined together along with hand picked winter veggies and fresh cut salsa which makes this bowl the best pick of the season.\nEnergy 541 Kcal, Fat 24 gms, Carbs 60 gms, Fiber 6 gms, Protein 21 gms",
    i: 12949,
    t: "Signature Roast Rice Bowls",
    shd: "Rice, Mierpoix, Mushroom, Jalapeno, Tomato Salsa, Sour Cream.",
    mainCategory: "Superbowls",
    p: 149,
    mrp: 299,
    im: "https://d3gy1em549lxx2.cloudfront.net/163820df-60ed-473e-b89a-3fe0ae38e728.JPG",
    ct: ["lunch", "dinner"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "This Middle Eastern street food favorite is now available in a convenient bowl format, bringing the authentic taste of shawarma to your table. Indulge in this delightful combination of spices, succulent chicken for a truly satisfying culinary experience. Enjoy tender marinated paneer stacked and roasted to perfection, served over a bed of flavorful rice.\nEnergy 455 Kcal, Carbs 50 gms, Protein 17 gms, Fiber 4 gms, Fat 21 gms",
    i: 13424,
    t: "Shawarma Paneer Rice Bowls",
    shd: "Shawarma Paneer, Rice, Chickpeas, Glace Sauce, Hung Curd, Lemon juice.",
    mainCategory: "Bowls",
    p: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/51920f9c-423c-4dd3-ab84-908b706f2b5e.JPG",
    ct: ["lunch", "dinner"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "FreshMenu's signature Teriyaki Rice Bowls is an all time favourite meal with our guests. Diced, grilled veges, leeks, broccoli, bell peppers, carrot and Chinese cabbage are seasoned, sautéed and simmered in a rice-wine vinegar infused japanese teriyaki sauce. Served with a portion of vegetable fried-rice. May contain mushrooms. All our bowls are prepared fresh on your order.\nEnergy 475 Kcal, Fat 23 gms, Carbs 50 gms, Fiber 1 gms, Protein 20 gms",
    i: 10372,
    t: "Teriyaki Veg Rice Bowls",
    shd: "Rice, Carrot, Green Bean, Rice-Wine Vinegar, Red Chilli, Light Soy Sauce, Dark Soy Sauce, Teriyaki Sauce, Bell Pepper",
    mainCategory: "Bowls",
    p: 149,
    mrp: 299,
    im: "https://d3gy1em549lxx2.cloudfront.net/dbd26c3e-897d-4d4b-8ab3-c2e93d7fdbfa.jpg",
    ct: ["lunch", "dinner"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "A spicy and creamy dish that's just bursting with flavor. Tossed with bell peppers, juicy onions and chunks of paneer, it's the perfect meal for any occasion\nEnergy 291 Kcal, Fat 7 gms, Carbs 53 gms, Fiber 3 gms, Protein 6 gms",
    i: 12771,
    t: "Dragon Paneer Rice Bowls",
    shd: "Paneer, Rice, Bell pepper Onion",
    mainCategory: "Bowls",
    p: 149,
    mrp: 299,
    im: "https://d3gy1em549lxx2.cloudfront.net/193aac3a-f8e5-464b-8075-fb382c932026.jpg",
    ct: ["lunch", "dinner"],
  },

  {
    thirdPartyDescription:
      "From Italy with love. This classic pasta is made with everything from zucchini to mushrooms. Then mixed with creamy mushroom sauce for flavour and generous amounts of parmesan cheese. Garnished with black olives. All our meals are prepared fresh on order.\nEnergy 434 Kcal, Carbs 51 gms, Protein 13 gms, Fiber 3 gms, Fat 20 gms",
    i: 11062,
    t: "Creamy Mushroom Pasta",
    shd: "Penne pasta, zuchhini, mushrooms, olives, fresh basil, fresh cream, herbs",
    mainCategory: "Pasta",
    p: 149,
    mrp: 299,
    im: "https://d3gy1em549lxx2.cloudfront.net/614111e2-7e40-4ce8-bedc-7075fa746ba0.JPG",
    ct: ["snacking", "party"],
  },
  {
    thirdPartyDescription:
      "Ready? Say Cheese! American best seller, Italiano Classic Mac N Cheese is a dish that has evolved from a mini lasagna casserole to cheesy mac bake combined with Peri Peri potato strips and green pepper mustard sauce completes the meal- deal. The classic mac n cheese, is the rich, creamier way to dig into the bowl with loads of cheese, winter veggies and goodness. It is more than just good. It’s spectacular!\nEnergy 700 Kcal, Carbs 63 gms, Protein 33 gms, Fiber 7 gms, Fat 36 gms",
    i: 12918,
    t: "Classic Mac n Cheese Steak Meal",
    shd: "Macaroni Pasta, Peri Peri Seasoning, Sauce.",
    mainCategory: "Pasta",
    p: 149,
    mrp: 299,
    im: "https://d3gy1em549lxx2.cloudfront.net/4f53d9ea-819c-4d45-97ff-278b3b9e0274.jpg",
    ct: ["snacking", "party"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Delicious paneer tikka cooked in a rich makhani gravy served on a bed of aromatic coriander peas pulao. Our signature combo is pretty popular and its sure to leave you feeling awesome!\nEnergy 591 Kcal, Fat 27 gms, Carbs 63 gms, Fiber 8 gms, Protein 24 gms",
    i: 4462,
    t: "Paneer Butter Masala Bowls",
    shd: "Paneer, Rice, Cashew, Butter, Garam Masala, Cream, Coriander, Dried Fenugreek, Ginger, Honey",
    mainCategory: "Bowls",
    p: 149,
    mrp: 299,
    im: "https://d3gy1em549lxx2.cloudfront.net/e71d5d3d-d9cc-46e0-b0ad-84bc99e677c8.jpg",
    ct: ["lunch", "dinner"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "This bowl contains mexican tomato rice loaded with toppings to give you a full-satisfying meal. Fresh paneer cubes, corn-bean,tangy tomato pineapple salsa and sour cream garnished with jalapeno and cheese. Packed with a burst of flavours. All our meals are prepared fresh on order.\nNote: Broccoli may be replaced with green beans due to seasonality constraint.\nEnergy 370 Kcal, Fat 26 gms, Carbs 23 gms, Fiber 7 gms, Protein 26 gms",
    i: 10334,
    t: "Ultimate Burrito Bowls",
    shd: "Rice, Tomato, Paneer,sweet corn, Onion, jalapeno,black olives, red-kidney beans , cheese, sour cream, pineapple",
    mainCategory: "Bowls",
    p: 149,
    mrp: 299,
    im: "https://d3gy1em549lxx2.cloudfront.net/51828e9b-1b09-4c49-8d32-5cd0c5b3ed90.JPG",
    ct: ["lunch", "dinner"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Savor the umami-popping Mushroom Teriyaki Tacos, which have soft tortillas encasing sautéed mushrooms drenched in delicious teriyaki sauce. A dash of sesame seeds finishes off this flavorful taco experience. Layers of flavor are added by the harmony of garlic mayo, crisp lettuce, and the strong kick of kimchi.",
    i: 14117,
    t: "Mushroom Teriyaki Tacos",
    shd: "Tortilla, Garlic Mayo, Lettuce, Kimchi, Mushroom, Sesame",
    mainCategory: "Wraps",
    p: 149,
    mrp: 239,
    im: "https://d3gy1em549lxx2.cloudfront.net/36877413-ff0b-47be-9d13-1b22f617adf1.jpg",
    ct: ["snacking", "party"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Savor the earthy and rich flavors of Pepper Mushroom Tacos, which feature tender chicken and savory mushrooms wrapped in soft tortillas, all topped off with a refreshing mint mayo. This taco experience is enhanced by the addition of crisp lettuce and a sprinkle of cheese, which combines flavors and textures in a way that is pleasing to the palate.",
    i: 14115,
    t: "Pepper Mushroom Tacos",
    mainCategory: "Wraps",
    p: 149,
    mrp: 239,
    im: "https://d3gy1em549lxx2.cloudfront.net/1290cb16-f2b7-45fc-9bf7-059a36b82cc5.jpg",
    ct: ["snacking", "party"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Take a bite out of Paneer 65 Tacos, a fusion delicacy that combines expertly seasoned paneer with the comforting warmth of tortillas and a spicy kick from Peri Peri Mayo. A delightful blend of spice and zest is added to every bite with the crisp lettuce and tart pickled onions providing a crisp and refreshing crunch.",
    i: 14110,
    t: "Paneer 65 Tacos",
    shd: "Paneer, Tortilla, Peri Peri Mayo, Lettuce, Pickled Onion",
    mainCategory: "Wraps",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/b1b781cc-8a3d-4605-b8d6-71cd0223a252.jpg",
    ct: ["party", "snacking"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "This hot favourite is launched new on our menu! Juicy burger is made with a breaded fried chicken with peri peri flavour, layered with fresh crunchy lettuce, tomato, onion and peri-peri cheese mix, in between home-baked fresh butter toasted buns. We’re thinking this is a bite you’d hate to miss out on!\nEnergy 682 Kcal, Fat 39 gms, Carbs 53 gms, Fiber 3 gms, Protein 26 gms.",
    i: 12335,
    t: "Peri Peri Double Chicken Burger",
    st: "Peri Peri Double Chicken Burger",
    d: "This hot favourite is launched new on our menu! Juicy burger is made with a breaded fried chicken with peri peri flavour, layered with fresh crunchy lettuce, tomato, onion and peri-peri cheese mix, in between home-baked fresh butter toasted buns. We’re thinking this is a bite you’d hate to miss out on!",
    shd: "Chicken leg, burger bun, lettuce, onion, tomato, gherkins, cheese sauce, mayonnaise, tomato salsa, peri peri seasoning, cheese slice, butter",
    mainCategory: "Burgers",
    p: 149,
    mrp: 249,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/273fdede-1052-4958-b901-eabc545d045c.JPG",
    lc: 2,
    il: false,
    ia: true,
    ica: false,
    pdt: [
      {
        id: 26778,
        startTime: 660,
        endTime: 1438,
        mdt: 45,
      },
    ],
    c: [
      {
        id: 22,
        name: "Non Veg",
        categoryType: "COURSE",
      },
      {
        id: 43,
        name: "Burgers",
        categoryType: "COURSE",
      },
    ],
    ct: ["snacking","party"],
    cu: {
      i: 1,
      n: "Continental",
    },
    iv: true,
    slg: "continental_peri_peri_double_chicken_burger",
    su: "https://fmln.in/pxdFuDs",
    bds: [],
    flts: ["A_N"],
    at: "ADD_TO_CART",
    fi: [102, 52],
    sn: 9,
    egg: false,
  },
  {
    thirdPartyDescription:
      "Introducing our new uniquely tall burger that will take your taste buds to the next level! This burger is stacked with chargrilled Moroccan paneer, fresh garden veggies, crisp lettuce, zesty coleslaw, spicy jalapenos, hearty ratatouille, creamy cheese, and topped with tangy beetroot lebneh. Every bite is a flavor explosion that will leave you craving more. Try it today and experience the ultimate burger experience!\nEnergy 423 Kcal, Carbs 46 gms, Protein 18 gms, Fiber 3 gms, Fat 18 gms",
    i: 13313,
    t: "Double Decker Moroccan Veggie Burger",
    shd: "Burger Bun, Mixed Lettuce, Veg Pattie, Ratattoullie, Beetroot Labneh, Jalapeno.",
    mainCategory: "Burgers",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/8dcdcb57-b930-4952-b7b0-44fdc304a118.JPG",
    ct: ["snacking", "party"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Peri-peri marinated cottage cheese steak is grilled to perfection, placed on a bed of fresh crunchy lettuce, onion, tomato and jalapenos. Loaded with cheese sauce and cheese slice in our inhouse wholewheat buns.ENERGY (KCAL) - 654, Carbs (g) -39, Protein (g) -19, Fat (g) -5 , Fiber (g) - 1, Sodium, Na (mm) -1,582.00 Sugar(g) - 0",
    i: 12121,
    t: "Peri Peri Paneer Steak Burger",
    shd: "Paneer steak, Burger Bun, Peri-peri seasoning, thousand island spread, lettuce, Onion, tomato, jalapenos, cheese sauce, worcestershire sauce, garlic, parsley, gouda cheese, bbq sauce, butter",
    mainCategory: "Burgers",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/edba82ff-548c-4a4e-a43e-5185b26c3fdb.JPG",
    ct: ["snacking", "party"],
    egg: false,
  },
  {
    thirdPartyDescription:
      '"Double your delight with our mouthwatering Double-Decker Spicy Grilled Chicken. Indulge in succulent, flavorful chicken infused with mexican spices, paired with fresh veggies, crisp lettuce, and coleslaw. Packed with protein, vitamins, fiber, and the irresistible goodness of melted cheese, it\'s a satisfying treat that satisfies cravings while providing essential nutrients.\nEnergy 484 Kcal, Carbs 35 gms, Protein 25 gms, Fiber 1 gms, Fat 29 gms"',
    i: 13221,
    t: "Double Decker Mexicano Chicken Burger",
    shd: "Burger Bun, Garlic Aioli, Peri Peri Chicken Strips, Tomato Relish, Olives, Cheese Slice.",
    mainCategory: "Burgers",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/0148b839-6131-4046-bc7b-0351b86a94aa.jpg",
    ct: ["snacking", "party"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Experience the flavour of freshly baked soft burger buns stuffed with a layer of spicy birds eye paneer, fresh lettuce, thinly sliced onion, and juicy tomato. The other layer has a tonne of gooey cheese, tangy mustard sauce, and crunchy coleslaw that will make you want more. Get ready to enjoy this delicious burger on your own -- you won't want to share!\nEnergy 529 Kcal, Carbs 48 gms, Protein 21 gms, Fiber 3 gms, Fat 29 gms",
    i: 13314,
    t: "Double Decker Bird Eye Paneer Burger",
    shd: "Burger Bun, Veg Pattie, Peri Peri Bird's Eye Paneer, Mixed Lettuce, Slaw, Olives, Cheese",
    mainCategory: "Burgers",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/1378d9ec-04b4-4e06-92e1-faef23657749.JPG",
    ct: ["snacking", "party"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Try our new double-layered, extra-spicy veggie burger, bursting with fresh, flavorful ingredients. The first layer features a fried veggie patty, crisp lettuce, juicy tomatoes, and zesty onions. The second layer delights with zattar-spiced roasted eggplant, creamy coleslaw, tangy jalapenos, and a rich cheese slice—a symphony of flavors that'll leave you craving for more.\nEnergy 455 Kcal, Carbs 52 gms, Protein 20 gms, Fiber 3 gms, Fat 19 gms",
    i: 13312,
    t: "Double Decker Zaatar Veggie Burger",
    shd: "Burger Bun, Mixed Lettuce, Veg Pattie, Peri Peri Hummus, Roasted Egg Plant, Cheese Slice, Jalapeno.",
    mainCategory: "Burgers",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/2f57bc9b-5e59-40b8-af3d-f92fcc67be45.JPG",
    ct: ["party", "snacking"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Enjoy our Iron Man Omelette, a delicious combination of fluffy eggs, stuffed with a mix of cheese, spinach, and corn, finished with a sprinkle of fresh parsley, to experience the superhero flavors. This omelette is a taste powerhouse that will send your taste senses skyward.\nEnegry-132 Kcal, Fat-9.31 gms, Carbs-3.27 gms, Fiber-0.7 gms, Protein-8.75 gms,",
    i: 13738,
    t: "Iron-Man Omelette",
    shd: "Egg, Crushed Black Pepper, Cheese, Spinach and Corn,Cheese, Parsley",
    mainCategory: "Breakfast",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/8e80ce68-16bb-4669-8cc8-6ea312d94f7c.jpg",
    ct: ["breakfast"],
    egg: true,
  },
  {
    thirdPartyDescription:
      "A mix of bite sized pineapple, watermelon, muskmelon, papaya, apple, pomegranate; perfect to brighten up your day in the morning and fuel you up for the rest of the day. Energy 345 kcal,Fat 9g, Carbs 59g ,Fiber 8g,Protein 6g",
    i: 12227,
    t: "Fresh Fruit Bowls",
    im: "https://d3gy1em549lxx2.cloudfront.net/9a64f309-8acb-468f-a31c-17291707957e.JPG",
    shd: "Watermelon, Apple, Muskmelon, Pineapple, Papaya, Pomegranate, Honey, Mint leaf",
    mainCategory: "Breakfast",
    p: 149,
    bsp: 149,
    ct: ["breakfast"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Scrambled eggs, sausages tossed in a special seasoning are served alongside a hash brown. This blend isn't just perfect for starting your day, but also great to get you through your busy schedule. Order now. ENERGY 436kcal, Fat 32g, Carbs  18g, Fiber 3g,  Protein 20g",
    i: 10340,
    t: "High Protein English breakfast",
    st: "High Protein English breakfast",
    d: "Scrambled eggs, sausages tossed in a special seasoning are served alongside a hash brown. This blend isn't just perfect for starting your day, but also great to get you through your busy schedule. Order now.",
    shd: "Yellow Cheddar, Chicken Sausage, Panko Crumbs, Parsley, Black Pepper, Bell Peppers, Potato, Butter, Eggs",
    mainCategory: ["Breakfast"],
    p: 149,
    mrp: 249,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/8ff101f1-3656-48d0-a694-a0af13763a1d.JPG",
    lc: 50,
    il: false,
    ia: true,
    ica: false,
    pdt: [
      {
        id: 20920,
        startTime: 445,
        endTime: 1438,
        mdt: 45,
      },
    ],
    c: [
      {
        id: 57,
        name: "breakfast",
        categoryType: "COURSE",
      },
      {
        id: 22,
        name: "Non Veg",
        categoryType: "COURSE",
      },
      {
        id: 154,
        name: "New2020",
        categoryType: "COURSE",
      },
    ],
    ct: ["breakfast"],
    cu: {
      i: 1,
      n: "Continental",
    },
    iv: true,
    slg: "continental_high_protein_english_breakfast",
    su: "https://fmln.in/pxmfmGW",
    bds: [],
    flts: ["A_N"],
    at: "ADD_TO_CART",
    fi: [102, 52],
    sn: 10,
    egg: false,
  },
  {
    thirdPartyDescription:
      "Indulge in a fusion of flavours with our chef's handcrafted dish. Enjoy pan-seared focaccia cubes, baked beans, onion tomato masala, and a vibrant veggie mix. Topped with Moroccan paneer, hashbrown, jalapenos, and fresh parsley for a culinary delight.\nEnergy 259 Kcal, Carbs 36 gms, Protein 9 gms, Fiber 5 gms, Fat 10 gms",
    i: 13375,
    t: "Paneer Power breakfast",
    shd: "Pan Seared Focaccia Cubes, Baked Beans, Onion Tomato Masala, Veggie Mix, Morrocoan Paneer, Diced Hashbrown, Sliced Jalapenos, Chopped Parsley.",
    mainCategory: "Breakfast",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/13701742-72d1-4214-8e0a-dbcb7507f99f.JPG",
    ct: [ "breakfast"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "A protein packed breakfast for you to relish. Scrambled eggs, sausages tossed in a special seasoning and this blend isn't just perfect for starting your day, but also great to get you through your busy schedule. Order now.\nEnergy 198 Kcal, Carbs 3 gms, Protein 12 gms, Fat 15 gms",
    i: 13106,
    t: "Creamy Egg Sausage Brekkie",
    shd: "Scrambled Eggs, Cheese, Onions, Tomato, Sausages",
    mainCategory: "Breakfast",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/49b86753-1fdb-44ea-bf2b-f993382ee6da.jpeg",
    ct: [ "breakfast"],
    egg: true,
  },
  {
    thirdPartyDescription:
      "Introducing the all-new breakfast bowl, The Muscle Multiplier. It is a combination of high-protein baked beans, cheesy boiled eggs,  with a side of hashbrown \nEnergy 295 Kcal, Carbs 24 gms, Protein 18 gms, Fiber 2 gms, Fat 14 gms",
    i: 13267,
    t: "The Muscle Multiplier",
    shd: "Egg, Sub Toast, Baked Beans, Tomato Salsa, Cheese.",
    mainCategory: "Breakfast",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/f076432f-7bc9-4e02-9f19-5efadf9c6f67.jpeg",
    ct: ["breakfast"],
    egg: true,
  },
  {
    thirdPartyDescription:
      "The Viking breakfast is all you need to kick start your day, curated combination of cheesey spinach corn, protein rich baked beans, hashbrown and basil tomato salad \nEnergy 309 Kcal, Carbs 41 gms, Protein 6 gms, Fiber 4 gms, Fat 14 gms",
    i: 13244,
    t: "The V-King",
    shd: "Spinach Corn Filling, Hash Brown, Baked Beans, Tomato Basil Salsa.",
    mainCategory: "Breakfast",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/1811b834-4c65-47d7-967d-13fecc98a9c6.jpg",
    ct: ["breakfast"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Experience the original flavors of a typical French breakfast with our delightful bowl. Our take on this French toast combines the classic dish of bread soaked in a rich custard made with Eggs, milk, cream and sugar griddled to perfection. Indulge in this savory and satisfying treat, perfect for on-the-go snacks or a power-packed protein snack.\nEnergy 449 Kcal, Carbs 63 gms, Protein 17 gms, Fiber 3 gms, Fat 16 gms",
    i: 13378,
    t: "Classic French Toast Combo",
    shd: "Focaccia, Milk, Egg, Banana, Apple, Papaya, Pomegranate, Pancake Syrup Drizzle, \nMint.",
    mainCategory: "Breakfast",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/095e0261-05f7-457c-a4c3-b11717c034b8.jpeg",
    ct: ["breakfast"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Let the morning unfold with The SP-rinter. Power packed with cheesy spnach and corn, paneer burji, baked beans, tomato basil salad \nEnergy 229 Kcal, Carbs 28 gms, Protein 7 gms, Fiber 3 gms, Fat 11 gms",
    i: 13254,
    t: "The Sprinter",
    shd: "Spinach Corn Filling, Paneer Bhurji, Baked Beans, Tomato Basil Salad.",
    mainCategory: "Breakfast",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/781606cc-ad51-47c9-bc3c-a25a7cce9250.jpeg",
    ct: ["breakfast"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "This is a good addiction for a great start of the day, Masala sausage omelette, golden hashbrown, grilled sausage and tomato salsa\nEnergy 305 Kcal, Carbs 24 gms, Protein 13 gms, Fiber 2 gms, Fat 18 gms",
    i: 13248,
    t: "The Sausagaddict",
    shd: "Egg  & Sausage Omelette, Hash Brown, Tomato Salsa, Black Pepper, Chilli Flakes, Sub Toast.",
    mainCategory: "Breakfast",
    p: 99,
    bsp: 99,
    im: "https://d3gy1em549lxx2.cloudfront.net/d5bdd680-6a72-450d-92a7-92a8ebf948fa.JPG",
    ct: ["breakfast"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Discover a delightful on-the-go snack inspired by the ancient Roman Empire. Our French toast features sliced bread sandwiched with gooey cheddar cheese and soaked a rich custard and grilled to a golden brown. A power-packed protein treat with a touch of history to satisfy your cravings anytime.\nEnergy 390 Kcal, Carbs 62 gms, Protein 14 gms, Fiber 3 gms, Fat 14 gms",
    i: 13377,
    t: "Cheese French Toast Combo",
    shd: "Focaccia, Cheese ,Milk, Egg, Banana, Apple, Papaya, Pomegranate, Pancake Syrup Drizzle, Mint.",
    mainCategory: "Breakfast",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/56c3cf9c-7ebb-4084-8017-2ff990fe181f.jpeg",
    ct: ["breakfast"],
    egg: true,
  },
  {
    thirdPartyDescription:
      "Introducing our new quinoa Mix Super Grain Upma Bowls! Made with a flavorful blend of quinoa, veggies, and spices, this dish is both healthy and delicious. Tossed with mustard, green chili, and curry leaves, and garnished with red chili and coriander, it's the perfect meal for anyone looking for a flavorful and nutritious option.\nEnergy 310 Kcal, Carbs 32 gms, Protein 6 gms, Fiber 4 gms, Fat 18 gms",
    i: 13308,
    t: "Super Grain Upma",
    shd: "Quinoa, Brown Rice, Wheat, Foxtail, Veggies, Ghee, Milk, lemon wedge.",
    mainCategory: "Breakfast",
    p: 99,
    bsp: 99,
    im: "https://d3gy1em549lxx2.cloudfront.net/c6742ee8-d99e-4e8e-ac2e-414bbda24e11.JPG",
    ct: ["breakfast"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Introducing the NV King, it is protein packed breakfast platter with single omelette, Cheesey pulled chicken, baked beans, gouda cheese sauce and tomato salsa, \nEnergy 321 Kcal, Carbs 21 gms, Protein 19 gms, Fiber 2 gms, Fat 17 gms",
    i: 13242,
    t: "The NV King",
    shd: "Egg Omelette, Chicken, Baked Beans, Sausage, Black Pepper, Chilli Flakes, Sub Toast",
    mainCategory: "Breakfast",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/9e4b36b2-08be-4dec-85ba-d6e72d60881a.JPG",
    ct: ["breakfast"],
    egg: true,
  },
  {
    thirdPartyDescription:
      "Not a meat lover, no problem. All the protein that you need is packed in this compact yet lavish breakfast. Masala omelette, cheesey spinach corn, baked beans and hashbrown \nEnergy 348 Kcal, Carbs 33 gms, Protein 10 gms, Fiber 3 gms, Fat 21 gms",
    i: 13250,
    t: "The Greenhouse",
    shd: "Masala Omelette, Hash Brown, Baked Beans, Spinach Corn Filling, Sub Toast",
    mainCategory: "Breakfast",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/8106fd2e-4c9b-498b-99db-5f7034dfd859.jpeg",
    ct: ["breakfast"],
    egg: true,
  },
  {
    thirdPartyDescription:
      "The Coach breakfast, the new way to start your day. A protein rich sausage and egg scramble, Hashbrown, sour cream and tomato basil salad \nEnergy 353 Kcal, Carbs 24 gms, Protein 13 gms, Fiber 1 gms, Fat 23 gms",
    i: 13256,
    t: "The Coach",
    shd: "Sausage and Egg Scramble, Hash Brown, Sour Cream, Tomato Basil Salad",
    mainCategory: "Salad",
    im: "https://d3gy1em549lxx2.cloudfront.net/8a39396c-6b61-4a80-94f2-8b1fe92bf25d.jpg",
    p: 149,
    bsp: 149,
    ct: ["breakfast"],
    egg: true,
  },
  {
    thirdPartyDescription:
      "Keeping an eye on your protien intake, this is your bowl of go-to goodness. Creamy eggwhite scrambles accompanied with grilled sausages, baked beans and fresh tomato basil salad \nEnergy 366 Kcal, Carbs 22 gms, Protein 18 gms, Fiber 2 gms, Fat 23 gms",
    i: 13252,
    t: "The Power BF",
    shd: "Egg White Scramble, Sausage, Baked Beans, Tomato Basil, Black Pepper",
    mainCategory: "Breakfast",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/0d710e0d-55b9-4cf9-89f2-5bad5530a5db.JPG",
    ct: ["breakfast"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "A mouth watering Paneer tikka combined with lettuce, roasted vegetables, beans and salsa to make a delicious Mexican style Indian inspired salad meal that’s both healthy and tasty.\nEnergy 625 Kcal, Fat 30 gms, Carbs 67 gms, Fiber 6 gms, Protein 23 gms",
    i: 12895,
    t: "Paneer Tikka Veggie Delight",
    shd: "Paneer tikka, Roasted Root veg, Tomato salsa, Mixed Lettuce, Onion, Tomato, Cucumber, Garbanzo beans, Jalapeno, Black Olives, Chopped parsley, Peri-peri bbq Dressing",
    mainCategory: "Salads",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/edb5d8ce-0f98-40c5-b125-c39d523fbf9a.jpg",
    ct: ["Veg", "Salads"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Our Mexican Style Pomo Salad is a cool and refreshing salad that's a perfect match for any meal. Made with our signature blend of hand-selected vegetables, crunchy lettuce, pomogranate, black olives & Thousand Island dressing, this salad has just the right amount of crunch and tangy taste!\nEnergy 373 Kcal, Fat 21 gms, Carbs 26 gms, Fiber 9 gms, Protein 20 gms",
    i: 12885,
    t: "Mexican Paneer Pomo Salad",
    shd: "Grilled paneer, Tri bellpepprs, Pomegrante, Mixed Lettuce, Onion, Tomato, Cucumber, Garbanzo beans, Processed cheese, Black Olives, Chopped parsley, Thousand island dressing",
    mainCategory: "Salads",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/9d228cca-f4f1-4454-96c3-a510bf601da8.jpg",
    ct: ["lunch", "dinner"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "This hearty, refreshing salad is all you need this summer. Diced cucumber, tomatoes, jalapeno, olives, roasted corn, kidney beans are tossed with lettuce and seasoned to perfection. Served with cumin-vinaigrette dressing.\nEnergy 239 Kcal, Carbs 46 gms, Protein 9 gms, Fiber 8 gms, Fat 4 gms",
    i: 13351,
    t: "Mini Corn Cucumber Bean Salad",
    st: "Mini Corn Cucumber Bean Salad",
    d: "This hearty, refreshing salad is all you need this summer. Diced cucumber, tomatoes, jalapeno, olives, roasted corn, kidney beans are tossed with lettuce and seasoned to perfection. Served with cumin-vinaigrette dressing.",
    shd: "Sweet Corn, Kidney beans, cucumber, tomato, Purple cabbage, jalapeno, olives, lettuce, cumin vinaigrette dressing",
    mainCategory: "Salads",
    p: 99,
    bsp: 99,
    im: "https://d3gy1em549lxx2.cloudfront.net/2503da8c-8e44-4462-85f4-da3ce1a09089.JPG",
    lc: 0,
    il: false,
    ia: true,
    ica: false,
    pdt: [
      {
        id: 28316,
        startTime: 660,
        endTime: 1438,
        mdt: 45,
      },
    ],
    c: [
      {
        id: 26,
        name: "Veg",
        categoryType: "COURSE",
      },
      {
        id: 44,
        name: "Salads",
        categoryType: "COURSE",
      },
    ],
    ct: ["Veg", "Salads"],
    cu: {
      i: 1,
      n: "Continental",
    },
    iv: true,
    slg: "continental_mini_corn_cucumber_bean_salad",
    su: "https://fmln.in/pxmemB5",
    bds: [],
    flts: ["A_N"],
    at: "ADD_TO_CART",
    fi: [102, 50, 51],
    sn: 8,
    egg: false,
  },
  {
    thirdPartyDescription:
      "A Turkish delight of grilled paneer, roasted root vegetables, red onion, tomato and assorted peppers, topped with crunchy, tangy pomegrante, olives and Gouda cheese dressing\nEnergy 373 Kcal, Fat 21 gms, Carbs 26 gms, Fiber 9 gms, Protein 20 gms",
    i: 12891,
    t: "Turkish Cottage Cheese And Chickpea Salad",
    st: "Turkish Cottage Cheese And Chickpea Salad",
    d: "A Turkish delight of grilled paneer, roasted root vegetables, red onion, tomato and assorted peppers, topped with crunchy, tangy pomegrante, olives and Gouda cheese dressing",
    shd: "Grilled paneer, Roasted Root veg, Tri bellpepprs, Mixed Lettuce, Onion, Tomato, Cucumber, Garbanzo beans, Pomegrante, Black Olives, Corriander leaf, Gouda cheese dressing",
    mainCategory: "Salads",
    p: 149,
    mrp: 299,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/4c7e5f4c-2c42-4d7a-9c18-fa5892c632c6.jpg",
    lc: 6,
    il: false,
    ia: true,
    ica: false,
    pdt: [
      {
        id: 27600,
        startTime: 660,
        endTime: 1438,
        mdt: 45,
      },
    ],
    c: [
      {
        id: 26,
        name: "Veg",
        categoryType: "COURSE",
      },
      {
        id: 44,
        name: "Salads",
        categoryType: "COURSE",
      },
    ],
    ct: ["Veg", "Salads"],
    cu: {
      i: 1,
      n: "Continental",
    },
    iv: true,
    slg: "continental_turkish_cottage_cheese_and_chickpea_salad",
    su: "https://fmln.in/pxmelkE",
    bds: [],
    flts: ["A_N"],
    at: "ADD_TO_CART",
    fi: [102, 50, 51],
    sn: 9,
    egg: false,
  },
  {
    thirdPartyDescription:
      "Nothing but the best combination of Citrus spiced peri-peri grilled chicken with all farm fresh veggies, lettuce, beans and smokey spicy barbeque dressing\nEnergy 470 Kcal, Fat 18 gms, Carbs 31 gms, Fiber 2 gms, Protein 46 gms",
    i: 12894,
    t: "Peri Peri Chicken Salad",
    st: "Peri Peri Chicken Salad",
    d: "Nothing but the best combination of Citrus spiced peri-peri grilled chicken with all farm fresh veggies, lettuce, beans and smokey spicy barbeque dressing",
    shd: "Peri peri chicken, Kidneybean, Cherry tomato, Mixed Lettuce, Onion, Tomato, Cucumber, Garbanzo beans, Processed cheese, Jalapeno, Chopped parsley, Peri-peri bbq Dressing",
    mainCategory: "Salads",
    p: 149,
    mrp: 299,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/32eae582-e319-4acf-89ee-07d4a9407205.JPG",
    lc: 3,
    il: false,
    ia: true,
    ica: false,
    pdt: [
      {
        id: 27603,
        startTime: 660,
        endTime: 1438,
        mdt: 45,
      },
    ],
    c: [
      {
        id: 22,
        name: "Non Veg",
        categoryType: "COURSE",
      },
      {
        id: 44,
        name: "Salads",
        categoryType: "COURSE",
      },
    ],
    ct: ["Non Veg", "Salads"],
    cu: {
      i: 1,
      n: "Continental",
    },
    iv: true,
    slg: "continental_peri_peri_chicken_salad",
    su: "https://fmln.in/pxmelrT",
    bds: [],
    flts: ["A_N"],
    at: "ADD_TO_CART",
    fi: [102, 52],
    sn: 10,
    egg: false,
  },
  {
    thirdPartyDescription:
      "This salad is a delightful combination of fresh ingredients that will satisfy your cravings for a healthy and flavorful meal. Enjoy a refreshing mix of mixed lettuce, blanched diced carrots, and broccoli, complemented by sautéed mushrooms and the tangy goodness of feta cheese and its a perfect winter treat that will tantalize your taste buds.\nEnergy 170 Kcal, Carbs 18 gms, Protein 5 gms, Fiber 5 gms, Fat 10 gms",
    i: 13396,
    t: "Moroccan Veggie Salad",
    st: "Moroccan Veggie Salad",
    d: "This salad is a delightful combination of fresh ingredients that will satisfy your cravings for a healthy and flavorful meal. Enjoy a refreshing mix of mixed lettuce, blanched diced carrots, and broccoli, complemented by sautéed mushrooms and the tangy goodness of feta cheese and its a perfect winter treat that will tantalize your taste buds.",
    shd: "Mixed Lettuce, Blanched Diced Carrots, Blanched Broccoli, Sauteed Mushroom, Chopped Parsley, Feta Cheese, Ginger Coriander Vinaigrette Dressing, Roasted Cumin Powder",
    mainCategory: "Salads",
    p: 149,
    mrp: 299,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/9a1648ef-4d74-42ee-aa7c-54e670dfecce.JPG",
    lc: 3,
    il: false,
    ia: true,
    ica: false,
    pdt: [
      {
        id: 28374,
        startTime: 660,
        endTime: 1438,
        mdt: 45,
      },
    ],
    c: [
      {
        id: 26,
        name: "Veg",
        categoryType: "COURSE",
      },
      {
        id: 44,
        name: "Salads",
        categoryType: "COURSE",
      },
    ],
    ct: ["Veg", "Salads"],
    cu: {
      i: 1,
      n: "Continental",
    },
    iv: true,
    slg: "continental_moroccan_veggie_salad",
    su: "https://fmln.in/pxhmlOc",
    bds: [],
    flts: ["A_N"],
    at: "ADD_TO_CART",
    fi: [102, 50, 51],
    sn: 11,
    egg: false,
  },
  {
    thirdPartyDescription:
      "Juicy grilled chicken dices get fancied up with the exotic and mesmerizing taste of bbq sauce. This delectable salad comes with all the locally sourced fresh veggies, scrumptious servings of kidney beans, grilled chicken, assorted hand-torn lettuce with herbs, all tossed in a cumin vinaigrette dressing. A perfect one-dish meal that you will love! Energy 311 Kcal, Fat 15.8 gms, Carbs 29 gms, Fiber 7.7 gms, Protein 16.6 gms.",
    i: 13353,
    t: "Mini BBQ-ed Chicken Salad",
    st: "Mini BBQ-ed Chicken Salad",
    d: "Juicy grilled chicken dices get fancied up with the exotic and mesmerizing taste of bbq sauce. This delectable salad comes with all the locally sourced fresh veggies, scrumptious servings of kidney beans, grilled chicken, assorted hand-torn lettuce with herbs, all tossed in a cumin vinaigrette dressing. A perfect one-dish meal that you will love!",
    shd: "Chicken dices, cucumber, sweet corn, tomato, black olives, jalapeno, parsley, hebs, lettuce, red rajma bean, bbq sauce",
    mainCategory: "Salads",
    p: 99,
    bsp: 99,
    im: "https://d3gy1em549lxx2.cloudfront.net/83c96326-ad21-47e9-ab0b-ce246f9ecdfd.JPG",
    lc: 3,
    il: false,
    ia: true,
    ica: false,
    pdt: [
      {
        id: 28318,
        startTime: 660,
        endTime: 1438,
        mdt: 45,
      },
    ],
    c: [
      {
        id: 22,
        name: "Non Veg",
        categoryType: "COURSE",
      },
      {
        id: 44,
        name: "Salads",
        categoryType: "COURSE",
      },
    ],
    ct: ["Non Veg", "Salads"],
    cu: {
      i: 1,
      n: "Continental",
    },
    iv: true,
    slg: "continental_mini_bbq_ed_chicken_salad",
    su: "https://fmln.in/pxgysDY",
    bds: [],
    flts: ["A_N"],
    at: "ADD_TO_CART",
    fi: [102, 52],
    sn: 12,
    egg: false,
  },
  {
    thirdPartyDescription:
      "This Mexican-inspired delight is a burst of flavors. Indulge in a vibrant and delectable salad with mixed lettuce, cucumber, and tomatoes. Savor the richness of boiled rajma and the boldness of peri peri pulled chicken. Topped with cherry tomatoes, zesty tomato salsa, cheese, and creamy Thousand Island dressing, providing both body and soul with a nourishing experience.\nEnergy 269 Kcal, Carbs 12 gms, Protein 13 gms, Fiber 3 gms, Fat 20 gms",
    i: 13413,
    t: "BBQ Ranch Chicken Salad",
    st: "BBQ Ranch Chicken Salad",
    d: "This Mexican-inspired delight is a burst of flavors. Indulge in a vibrant and delectable salad with mixed lettuce, cucumber, and tomatoes. Savor the richness of boiled rajma and the boldness of peri peri pulled chicken. Topped with cherry tomatoes, zesty tomato salsa, cheese, and creamy Thousand Island dressing, providing both body and soul with a nourishing experience.",
    shd: "Mixed Lettuce, Diced Onions, Diced Tomatoes, Diced Bell Peppers, Pulled Peri Peri Chicken in BBQ Sauce, Chopped Parsley, Sliced Jalapenos, Ceaser Deressing",
    mainCategory: "Salads",
    p: 149,
    mrp: 299,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/5b170a30-f13e-4312-bd37-580d455bd7bc.JPG",
    lc: 1,
    il: false,
    ia: true,
    ica: false,
    pdt: [
      {
        id: 28391,
        startTime: 660,
        endTime: 1438,
        mdt: 45,
      },
    ],
    c: [
      {
        id: 22,
        name: "Non Veg",
        categoryType: "COURSE",
      },
      {
        id: 44,
        name: "Salads",
        categoryType: "COURSE",
      },
    ],
    ct: ["Non Veg", "Salads"],
    cu: {
      i: 1,
      n: "Continental",
    },
    iv: true,
    slg: "continental_bbq_ranch_chicken_salad",
    su: "https://fmln.in/pxhmmuF",
    bds: [],
    flts: ["A_N"],
    at: "ADD_TO_CART",
    fi: [102, 52],
    sn: 16,
    egg: false,
  },
  {
    thirdPartyDescription:
      "We give the ultimate comfort food a creamy, garlicky spin, making it even more delectable. Topped off with cream, butter and a good sprinkle of fresh parsley, our Roasted Garlic Chicken Soup is what will perk you up even if you aren’t ill.\nEnergy 490 Kcal, Fat 33 gms, Carbs 17 gms, Fiber 3 gms, Protein 31 gms.",
    i: 2114,
    t: "Roasted Garlic Chicken Soup",
    shd: "Chicken, Garlic, Leek, Béchamel, Thyme, Carrot, Celery",
    mainCategory: "Soups",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/d2be14c8-b0d4-451c-82dd-2eaccac3e610.jpg",
    ct: ["Soup", "Non Veg", "FitnFab"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Enjoy the soothing embrace of Creamy Tomato Thyme Soup, a velvety blend of juicy tomatoes, onions, and carrots that is complemented by the richness of oil and butter. A divine symphony is created by combining cream, pizza pasta sauce, and a hint of thyme. It is then topped with a lovely garnish and made sumptuously smooth by adding refined wheat and milk.\nEnegry-173 Kcal, Fat-14.02 gms, Carbs-10.13 gms, Fiber-1 gms, Protein-2.29 gms,",
    i: 13749,
    t: "Creamy Tomato Thyme Soup",
    shd: "Tomato, Onion, Carrot, Oil, Butter, Pepper, Cream, Pizza Pasta Sauce, Garnish, Refined Flour, Milk",
    mainCategory: "Soups",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/39cc5a56-6704-4213-8951-b07a3e80c55a.jpg",
    ct: ["Veg", "Soup"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Cream of Spinach Corn, a decadent combination of cooked spinach and corn boiled in aromatic oil and covered in a silky white sauce, will heighten your senses. This delicious mixture is perfected with a salty stock water foundation, adding the richness of cheese, a hint of pepper, and a dollop of butter, and promises a symphony of sensations in every spoonful.",
    i: 13752,
    t: "Cream-Of Spinach Corn Soup",
    shd: "Ready Spinach and Corn Mixture, Oil, White Sauce, Cheese, Pepper, Butter, Stock Water",
    mainCategory: "Soups",
    p: 149,
    bsp: 149,
    im: "https://d3gy1em549lxx2.cloudfront.net/7f77580b-de38-49f8-93d3-d6f9b7d118fb.jpg",
    ct: ["Veg", "Soup"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Dark-chocolate ganache, cinnamon-brown-sugar sprinkle, strawberry compote and raisins packed into a flaky, buttery Danish pastry – we call it the BLISS roll!",
    i: 10401,
    t: "Chocolate Cinnamon Roll",
    shd: "Dark Chocolate, Strawberry Compote, Raisin, Cinnamon, Brown Sugar, Butter, Milk, Cream, Yeast, All-Purpose Flour",
    mainCategory: "Desserts",
    p: 79,
    bsp: 79,
    im: "https://d3gy1em549lxx2.cloudfront.net/cfef83f6-76cf-447a-beee-f904e7f5e901.JPG",
    ct: ["Veg", "Desserts"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "What’s better than a triple-flavoured cake? And when it’s vanilla, strawberry, dark chocolate layered perfectly and baked to excellence, you know you are only a click away from going nuts over our triple fantasy cake. Garnished with almond flakes, your company with a warm cup of tea is right here!",
    i: 12280,
    shd: "Strawberry flavour, vanilla, dark chocolate, almond flakes,  butter, all purpose flour, crumbles, sugar",
    mainCategory: "Desserts",
    p: 99,
    bsp: 99,
    im: "https://d3gy1em549lxx2.cloudfront.net/e5500a71-15c4-4b2e-ad0a-eda0b9f0ad77.jpg",
    egg: false,
  },
  {
    thirdPartyDescription:
      "A double-layered chocolate sponge and chocolate ganache extravaganza – creamy, chocolatey with indulgence in each bite!",
    i: 7946,
    t: "Homemade Chocolate-Cake",
    shd: "Dark Chocolate, Cocoa, Cream All-Purpose Flour",
    mainCategory: "Desserts",
    p: 99,
    bsp: 99,
    im: "https://d3gy1em549lxx2.cloudfront.net/8059ae5c-6153-430f-8b5e-0b84cd9aabe1.jpg",
    ct: ["party", "snacking"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Dark chocolate sponge layered with milk chocolate truffle and dark chocolate truffles, is sure to be a perfect treat. Double layers mean double fun!",
    i: 10431,
    t: "Choco Fudge Blackout Cake",
    shd: "Brownie sponge, milk chocolate, dark chocolate, cream",
    mainCategory: "Desserts",
    p: 99,
    bsp: 99,
    im: "https://d3gy1em549lxx2.cloudfront.net/b5f302fa-e2d5-43a6-ad07-56c9f0619299.JPG",
    ct: ["party", "snacking", "lunch"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "An eggless Canadian blue berry cake enhanced with the goodness of milk soaked oats folded with jaggery and butter and golden baked with homemade cinnamon-blue berry compote. A perfect breakfast treat... can be enjoyed as a dessert with a scoop of ice cream or with hot cocoa.\nEnergy 439 Kcal, Fat 21 gms, Carbs 53 gms, Fiber 2 gms, Protein 4 gms",
    i: 9042,
    t: "Blueberry Oatmeal Cake",
    shd: "Oats, Blueberries, Jaggery, Vanilla Extract",
    mainCategory: "Desserts",
    p: 99,
    bsp: 99,
    im: "https://d3gy1em549lxx2.cloudfront.net/3c8b5e1d-6dcd-4af6-81b4-e542566570ef.JPG",
    ct: ["party", "snacking", "lunch"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Love chocolate? Then this tender, luxurious layer cake is for you. With a ganache glaze and a fabulous filling, the indulgence is so worth it, freshly baked with much love by our chefs in-house!",
    i: 11158,
    t: "Dutch Truffle Cake",
    shd: "Dark Chocolate, Sponge, sugar, brownie, cream",
    mainCategory: "Desserts",
    p: 99,
    bsp: 99,
    im: "https://d3gy1em549lxx2.cloudfront.net/009fa3ec-fd88-4d4e-a941-b7032b38f332.JPG",
    ct: ["Veg", "S-Desserts"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "An exotic wild berry cake filled with Berries of the forest and a delicious Buttery Streusel Topping, a traditional recipe handed over through generations... the wild berry crumb cake is the perfect dessert for all occasions and also as a morning breakfast cake Energy 311.7 Kcal, Fat 14.8 gms, Carbs 41.6 gms, Fiber 0.9 gms, Protein 3.3 gms",
    i: 9512,
    t: "Crumble-Blueberry-Cake",
    shd: "Blueberry, Butter, sugar, blueberry compote, vanilla, cinnamon, honey",
    mainCategory: "Desserts",
    p: 99,
    bsp: 99,
    im: "https://d3gy1em549lxx2.cloudfront.net/f3d6fff1-eb8e-4372-9786-7abb56382fc9.JPG",
    ct: ["party", "dinner", "snacking"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Classic lemonade with a twist of Indian spices makes this invigorating drink a perfect Summer drink. Made with freshly squeezed lemon juice.",
    i: 14314,
    t: "Masala-Lemonade",
    shd: "Water, Sugar, Lemon Seasoning, Chaat Masala and  Black Salt",
    mainCategory: "Beverages",
    p: 79,
    bsp: 79,
    im: "https://d3gy1em549lxx2.cloudfront.net/be0709ea-742b-46fc-a15e-abdf11ef59da.jpg",
    ct: ["lunch", "party"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Beat the heat with this pack of buttermilk,  made with smoothly whipping-up curd, chaat masala, fragrant cumin powder and water. Garnished with fresh mint and coriander leaves, it surely quenches your thirst!\nEnergy 43.2 Kcal, Fat 3 gms, Carbs 2 gms,Protein 2 gms",
    i: 11300,
    t: "Mint Chaas",
    shd: "Curd, Cumin, Chaat masala, salt",
    mainCategory: "Beverages",
    p: 99,
    bsp: 99,
    im: "https://d3gy1em549lxx2.cloudfront.net/3867c0c8-6e4f-441e-8972-494790ce3070.JPG",
    ct: ["lunch"],
    egg: false,
  },
  {
    thirdPartyDescription:
      "Our tribute to the all-time-favourite lemonade with fresh mint leaves, lemon and water makes this refreshing drink an instant Summer cooler. A hint of black salt and sugar give that perfect finsh to this drink!",
    i: 11682,
    t: "Mint Lemonade",
    shd: "Lemon, mint leaves, water, black salt, sugar",
    mainCategory: "Beverages",
    p: 99,
    bsp: 99,
    im: "https://d3gy1em549lxx2.cloudfront.net/62a7864c-54e8-4aa9-8625-5858d6972259.jpg",
    ct: ["party", "snacking"],
    egg: false,
  },
];

export const reviewData = [
  {
    id: 1,
    title: "Yummy",
    content:
      "Mouth watering food from Greens and Grains. Everyone in family loved it. Thank you so much!!!",
    name: "Rahul Vaidya",
  },
  {
    id: 2,
    title: "Worth it!",
    content:
      "Great quality and quantity. Must try. Just what I needed post workout",
    name: "Kamal Pandey",
  },
  {
    id: 3,
    title: "Too good",
    content:
      "Great healthy options, totally loved each dish. Chicken Marylad for the win",
    name: "Abhishek Chaurasia",
  },
];
